title: Robert Brandhof
email: contact@robertbrandhof.com
description: >- # this means to ignore newlines until "baseurl:"
  le site de Robert BRANDHOF - peinture, dessin, lithographie, 
  livre d'artiste, Poterie de Ciboure, Pays Basque

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.robertbrandhof.com"
locale: fr_FR

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
   - .jekyll-cache/
   - .sass-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - README.md
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/